export const routes = {
  landing: "/",
  login: "/login",
  dashboard: "/dashboard",
  candidates: "/candidates",
  candidateDetail: (id: string) => `/candidates/${id}`,
  jobDescriptions: "/job-descriptions",
  jobDescriptionNew: "/job-descriptions/new",
  jobDescriptionEdit: (id: string) => `/job-descriptions/${id}/edit`,
  scoring: "/scoring",
  scoringResults: (matchRunId: string) => `/scoring/${matchRunId}`,
  chat: "/chat",
  chatSession: (sessionId: string) => `/chat/${sessionId}`,
  shortlists: "/shortlists",
  shortlistCollection: (id: string) => `/shortlists/collections/${id}`,
  outreach: "/outreach",
  interviewQuestions: "/interview-questions",
  interviewQuestionDetail: (id: string) => `/interview-questions/${id}`,
  settings: "/settings",
} as const;

// Pattern strings for the router itself (not link helpers).
export const routePatterns = {
  landing: "/",
  login: "/login",
  dashboard: "/dashboard",
  candidates: "/candidates",
  candidateDetail: "/candidates/:id",
  jobDescriptions: "/job-descriptions",
  jobDescriptionNew: "/job-descriptions/new",
  jobDescriptionEdit: "/job-descriptions/:id/edit",
  scoring: "/scoring",
  scoringResults: "/scoring/:matchRunId",
  chat: "/chat",
  chatSession: "/chat/:sessionId",
  shortlists: "/shortlists",
  shortlistCollection: "/shortlists/collections/:id",
  outreach: "/outreach",
  interviewQuestions: "/interview-questions",
  interviewQuestionDetail: "/interview-questions/:id",
  settings: "/settings",
} as const;
