export const routes = {
  landing: "/",
  login: "/login",
  authCallback: "/auth/callback",
  apply: (token: string) => `/apply/${token}`,
  publicInterview: (token: string) => `/interviews/${token}`,
  dashboard: "/dashboard",
  jobs: "/jobs",
  jobsNew: "/jobs/new",
  jobEdit: (jobId: string) => `/jobs/${jobId}/edit`,
  candidates: "/candidates",
  candidateDetail: (id: string) => `/candidates/${id}`,
  jobDescriptions: "/job-descriptions",
  jobDescriptionNew: "/job-descriptions/new",
  jobDescriptionEdit: (id: string) => `/job-descriptions/${id}/edit`,
  scoring: "/scoring",
  scoringResults: (matchRunId: string) => `/scoring/${matchRunId}`,
  chat: "/chat",
  chatSession: (sessionId: string) => `/chat/${sessionId}`,
  shortlists: "/shortlists",
  shortlistCollection: (id: string) => `/shortlists/collections/${id}`,
  outreach: "/outreach",
  interviews: "/interviews",
  interviewQuestions: "/interviews/templates",
  interviewQuestionDetail: (id: string) => `/interviews/templates/${id}`,
  interviewTemplates: "/interviews/templates",
  interviewTemplateDetail: (id: string) => `/interviews/templates/${id}`,
  interviewReport: (interviewSessionId: string) => `/interviews/reports/${interviewSessionId}`,
  settings: "/settings",
} as const;

// Pattern strings for the router itself (not link helpers).
export const routePatterns = {
  landing: "/",
  login: "/login",
  authCallback: "/auth/callback",
  apply: "/apply/:token",
  publicInterview: "/interviews/:token",
  dashboard: "/dashboard",
  jobs: "/jobs",
  jobsNew: "/jobs/new",
  jobEdit: "/jobs/:jobId/edit",
  candidates: "/candidates",
  candidateDetail: "/candidates/:id",
  jobDescriptions: "/job-descriptions",
  jobDescriptionNew: "/job-descriptions/new",
  jobDescriptionEdit: "/job-descriptions/:id/edit",
  scoring: "/scoring",
  scoringResults: "/scoring/:matchRunId",
  chat: "/chat",
  chatSession: "/chat/:sessionId",
  shortlists: "/shortlists",
  shortlistCollection: "/shortlists/collections/:id",
  outreach: "/outreach",
  interviews: "/interviews",
  interviewQuestions: "/interview-questions",
  interviewQuestionDetail: "/interview-questions/:id",
  interviewTemplates: "/interviews/templates",
  interviewTemplateDetail: "/interviews/templates/:id",
  interviewReport: "/interviews/reports/:interviewSessionId",
  settings: "/settings",
} as const;
