import { useEffect } from "react";

import { isVietnameseUi } from "@/lib/ui-language";

const exactTranslations = new Map<string, string>([
  ["Editorial Intelligence", "Trợ lý tuyển dụng thông minh"],
  ["No job selected", "Chưa chọn vị trí"],
  ["Dashboard", "Tổng quan"],
  ["Jobs", "Công việc"],
  ["Candidates", "Ứng viên"],
  ["Search candidates, JDs…", "Tìm ứng viên, JD…"],
  ["Scoring", "Chấm điểm"],
  ["AI Chat", "Trò chuyện AI"],
  ["Shortlists", "Danh sách chọn lọc"],
  ["Outreach", "Liên hệ"],
  ["Interview Prep", "Chuẩn bị phỏng vấn"],
  ["Settings", "Cài đặt"],
  ["Support", "Hỗ trợ"],
  ["Upload resume", "Tải lên hồ sơ"],
  ["Upload Resume", "Tải lên hồ sơ"],
  ["Upload resumes", "Tải lên hồ sơ"],
  ["Welcome back", "Chào mừng bạn quay lại"],
  ["Create an account", "Tạo tài khoản"],
  ["Start your 14-day free trial. No credit card required.", "Bắt đầu dùng thử miễn phí 14 ngày. Không cần thẻ tín dụng."],
  ["Enter your details to sign in to your workspace.", "Nhập thông tin để đăng nhập vào không gian làm việc của bạn."],
  ["Sign in with Google", "Đăng nhập với Google"],
  ["OR", "HOẶC"],
  ["Full name", "Họ và tên"],
  ["Email address", "Địa chỉ email"],
  ["Password", "Mật khẩu"],
  ["Forgot password?", "Quên mật khẩu?"],
  ["Please enter a valid email address.", "Vui lòng nhập địa chỉ email hợp lệ."],
  ["Creating account…", "Đang tạo tài khoản…"],
  ["Signing in…", "Đang đăng nhập…"],
  ["Create account", "Tạo tài khoản"],
  ["Sign in", "Đăng nhập"],
  ["Already have an account?", "Đã có tài khoản?"],
  ["Don't have an account?", "Chưa có tài khoản?"],
  ["Sign up", "Đăng ký"],
  ["The talent you've been searching for is already in your pipeline.", "Nhân sự bạn đang tìm kiếm đã có sẵn trong pipeline của bạn."],
  ["Stop digging through resumes. Start having meaningful conversations with the right candidates.", "Đừng tiếp tục lục tìm CV. Hãy bắt đầu những cuộc trao đổi có giá trị với đúng ứng viên."],
  ["Join", "Tham gia"],
  ["recruiters building better teams.", "nhà tuyển dụng đang xây dựng đội ngũ tốt hơn."],
  ["Workspace updated", "Đã cập nhật workspace"],
  ["Workspace created", "Đã tạo workspace"],
  ["Settings saved successfully.", "Đã lưu cài đặt thành công."],
  ["Interview invitation sent", "Đã gửi lời mời phỏng vấn"],
  ["Send interview invitation", "Gửi lời mời phỏng vấn"],
  ["Interview Report", "Báo cáo phỏng vấn"],
  ["Interview Notes", "Ghi chú phỏng vấn"],
  ["Interview completed", "Đã hoàn thành phỏng vấn"],
  ["Interview questions unavailable", "Chưa có câu hỏi phỏng vấn"],
  ["Interview link is invalid", "Liên kết phỏng vấn không hợp lệ"],
  ["The public interview token is missing.", "Thiếu mã truy cập phỏng vấn công khai."],
  ["Public AI Interview", "Phỏng vấn AI công khai"],
  ["Structured Screening Interview", "Phỏng vấn sàng lọc có cấu trúc"],
  ["Current question", "Câu hỏi hiện tại"],
  ["Next question", "Câu hỏi tiếp theo"],
  ["Submit answer", "Gửi câu trả lời"],
  ["Finish interview", "Kết thúc phỏng vấn"],
  ["Interview template", "Mẫu phỏng vấn"],
  ["Generate new set", "Tạo bộ câu hỏi mới"],
  ["Generate", "Tạo"],
  ["Interview questions", "Câu hỏi phỏng vấn"],
  ["Question import", "Nhập câu hỏi"],
  ["Candidates", "Ứng viên"],
  ["Candidate", "Ứng viên"],
  ["Job descriptions", "Mô tả công việc"],
  ["Job description", "Mô tả công việc"],
  ["New job", "Công việc mới"],
  ["Edit job", "Chỉnh sửa công việc"],
  ["Create job", "Tạo công việc"],
  ["Delete job", "Xóa công việc"],
  ["Manage hiring workspaces and choose the active context for your recruiting pipeline.", "Quản lý các workspace tuyển dụng và chọn ngữ cảnh đang hoạt động cho pipeline của bạn."],
  ["Search jobs", "Tìm công việc"],
  ["Search jobs...", "Tìm công việc..."],
  ["Updated", "Cập nhật"],
  ["Created", "Tạo lúc"],
  ["Open", "Mở"],
  ["Set current", "Đặt làm hiện tại"],
  ["Edit job description", "Sửa mô tả công việc"],
  ["Score this job", "Chấm điểm công việc này"],
  ["Candidate upload", "Tải hồ sơ ứng viên"],
  ["Link and QR", "Liên kết và QR"],
  ["Candidates can open this link or scan the QR code to submit a PDF resume.", "Ứng viên có thể mở liên kết này hoặc quét mã QR để gửi hồ sơ PDF."],
  ["Back to Jobs", "Quay lại danh sách công việc"],
  ["Save changes", "Lưu thay đổi"],
  ["Cancel", "Hủy"],
  ["Delete", "Xóa"],
  ["Edit", "Sửa"],
  ["Create", "Tạo"],
  ["Save", "Lưu"],
  ["Save draft", "Lưu nháp"],
  ["Mark as sent", "Đánh dấu đã gửi"],
  ["+ New message", "+ Tin nhắn mới"],
  ["Filter by candidate", "Lọc theo ứng viên"],
  ["Select a message", "Chọn một tin nhắn"],
  ["Pick any message from the list to read or edit it.", "Hãy chọn một tin nhắn trong danh sách để đọc hoặc chỉnh sửa."],
  ["Subject", "Tiêu đề"],
  ["Subject line…", "Dòng tiêu đề…"],
  ["Write your message here…", "Viết nội dung tin nhắn tại đây…"],
  ["Delete this message permanently?", "Xóa vĩnh viễn tin nhắn này?"],
  ["New collection", "Bộ sưu tập mới"],
  ["Create collection", "Tạo bộ sưu tập"],
  ["Delete collection", "Xóa bộ sưu tập"],
  ["Collection name…", "Tên bộ sưu tập…"],
  ["Collections", "Bộ sưu tập"],
  ["No collections yet", "Chưa có bộ sưu tập nào"],
  ["Create a collection to save and organize candidate shortlists.", "Hãy tạo một bộ sưu tập để lưu và sắp xếp danh sách ứng viên chọn lọc."],
  ["Go to Candidates", "Đi đến Ứng viên"],
  ["Add candidates to this collection from the Candidates list or via AI Chat shortlisting.", "Hãy thêm ứng viên vào bộ sưu tập này từ danh sách Ứng viên hoặc từ kết quả chọn lọc trong Trò chuyện AI."],
  ["Message the recruiter assistant…", "Nhắn cho trợ lý tuyển dụng…"],
  ["Send message", "Gửi tin nhắn"],
  ["Search, compare, and analyse your candidate pool using natural language.", "Tìm kiếm, so sánh và phân tích danh sách ứng viên bằng ngôn ngữ tự nhiên."],
  ["Manage parsed resumes and candidate profiles", "Quản lý hồ sơ đã phân tích và hồ sơ ứng viên"],
  ["Search by name or file…", "Tìm theo tên hoặc tệp…"],
  ["Uploaded", "Đã tải lên"],
  ["uploaded", "đã tải lên"],
  ["Processing", "Đang xử lý"],
  ["processing", "đang xử lý"],
  ["Select all", "Chọn tất cả"],
  ["Select row", "Chọn dòng"],
  ["Rows per page", "Số dòng mỗi trang"],
  ["Previous page", "Trang trước"],
  ["Next page", "Trang sau"],
  ["No results", "Không có kết quả"],
  ["Clear search", "Xóa tìm kiếm"],
  ["Table view", "Dạng bảng"],
  ["Grid view", "Dạng lưới"],
  ["Candidate not found", "Không tìm thấy ứng viên"],
  ["The candidate record could not be loaded.", "Không thể tải hồ sơ ứng viên."],
  ["Overview", "Tổng quan"],
  ["Resume PDF", "CV PDF"],
  ["Interviews", "Phỏng vấn"],
  ["Candidate profile unavailable", "Chưa có hồ sơ ứng viên"],
  ["Resume Info", "Thông tin hồ sơ"],
  ["Open PDF", "Mở PDF"],
  ["No outreach messages", "Chưa có tin nhắn liên hệ"],
  ["Draft recruiter outreach from the Outreach workspace when you want to contact this candidate.", "Hãy soạn tin nhắn liên hệ từ khu vực Liên hệ khi bạn muốn kết nối với ứng viên này."],
  ["No interview invitations", "Chưa có lời mời phỏng vấn"],
  ["Send a recruiter interview invitation for this candidate to create the interview link and track status.", "Hãy gửi lời mời phỏng vấn cho ứng viên này để tạo liên kết phỏng vấn và theo dõi trạng thái."],
  ["Workspace Ready", "Workspace đã sẵn sàng"],
  ["Your workspace is ready.", "Workspace của bạn đã sẵn sàng."],
  ["The job has been created. Next, upload resumes or add the full job description. Scoring and AI chat become much more useful once one of those data sources exists.", "Công việc đã được tạo. Tiếp theo, hãy tải hồ sơ lên hoặc thêm mô tả công việc đầy đủ. Chấm điểm và trò chuyện AI sẽ hữu ích hơn nhiều khi có một trong hai nguồn dữ liệu này."],
  ["Add job description", "Thêm mô tả công việc"],
  ["Recommended Flow", "Luồng đề xuất"],
  ["Add the full job description to define fit.", "Thêm mô tả công việc đầy đủ để xác định mức độ phù hợp."],
  ["Run scoring after both are available.", "Chạy chấm điểm khi cả hai dữ liệu đã sẵn sàng."],
  ["Use AI chat to explore the candidate pool.", "Dùng trò chuyện AI để khám phá danh sách ứng viên."],
  ["New Conversation", "Cuộc trò chuyện mới"],
  ["No conversations yet", "Chưa có cuộc trò chuyện nào"],
  ["Loading conversations…", "Đang tải cuộc trò chuyện…"],
  ["Previous 7 Days", "7 ngày trước"],
  ["Loading history…", "Đang tải lịch sử…"],
  ["Ask anything about your candidates", "Hỏi mọi điều về ứng viên của bạn"],
  ["Who has 5+ years of Python experience?", "Ai có hơn 5 năm kinh nghiệm Python?"],
  ["Find candidates with machine learning skills", "Tìm ứng viên có kỹ năng machine learning"],
  ["Show candidates available in New York", "Hiển thị ứng viên sẵn sàng làm việc tại New York"],
  ["Who has a Master's degree in Computer Science?", "Ai có bằng Thạc sĩ Khoa học Máy tính?"],
  ["AI Assistant may generate inaccurate information. Please verify critical data.", "Trợ lý AI có thể tạo ra thông tin chưa chính xác. Vui lòng kiểm tra lại các dữ liệu quan trọng."],
  ["Workspace job description", "Mô tả công việc của workspace"],
  ["This page follows the selected workspace. Manage the current job description from the active job context instead of treating it as a standalone resource.", "Trang này đi theo workspace đang được chọn. Hãy quản lý mô tả công việc hiện tại từ ngữ cảnh công việc đang hoạt động thay vì xem nó như một tài nguyên độc lập."],
  ["Open workspace", "Mở workspace"],
  ["No job description yet", "Chưa có mô tả công việc"],
  ["This workspace does not have a current JD yet. Create one here, then continue to scoring and interview preparation.", "Workspace này chưa có JD hiện tại. Hãy tạo tại đây, rồi tiếp tục sang chấm điểm và chuẩn bị phỏng vấn."],
  ["Current JD", "JD hiện tại"],
  ["Back to workspace", "Quay lại workspace"],
  ["This editor follows the currently selected workspace.", "Trình soạn thảo này đi theo workspace đang được chọn."],
  ["Bold", "In đậm"],
  ["Italic", "In nghiêng"],
  ["Heading 2", "Tiêu đề 2"],
  ["Bullet list", "Danh sách đầu dòng"],
  ["Untitled position", "Vị trí chưa đặt tên"],
  ["Start writing the job description… Use the toolbar to add headings, bold text, and bullet points.", "Bắt đầu viết mô tả công việc… Dùng thanh công cụ để thêm tiêu đề, chữ đậm và các gạch đầu dòng."],
  ["Deactivate", "Tắt kích hoạt"],
  ["Activate", "Kích hoạt"],
  ["Available for scoring", "Sẵn sàng để chấm điểm"],
  ["Not available for scoring", "Chưa sẵn sàng để chấm điểm"],
  ["Inactive", "Không hoạt động"],
  ["Delete JD", "Xóa JD"],
  ["Interview Templates", "Mẫu phỏng vấn"],
  ["Interview templates", "Mẫu phỏng vấn"],
  ["Create and maintain job-scoped interview scripts, questions, and report rubrics.", "Tạo và quản lý các kịch bản phỏng vấn, bộ câu hỏi và tiêu chí báo cáo theo từng công việc."],
  ["New template", "Mẫu mới"],
  ["Create Interview Template", "Tạo mẫu phỏng vấn"],
  ["Define the recruiter-facing template before sending interview invitations.", "Thiết lập mẫu dành cho nhà tuyển dụng trước khi gửi lời mời phỏng vấn."],
  ["Template name", "Tên mẫu"],
  ["Language code", "Mã ngôn ngữ"],
  ["Intro script", "Lời mở đầu"],
  ["Closing script", "Lời kết"],
  ["Import from list", "Nhập từ danh sách"],
  ["Question payload preview", "Xem trước bộ câu hỏi"],
  ["Report rubric", "Tiêu chí báo cáo"],
  ["Question list import", "Nhập danh sách câu hỏi"],
  ["Before you begin", "Trước khi bắt đầu"],
  ["This interview uses a fixed recruiter-approved question set. Your responses are transcribed and shared with the hiring team for review.", "Buổi phỏng vấn này sử dụng một bộ câu hỏi cố định đã được nhà tuyển dụng phê duyệt. Câu trả lời của bạn sẽ được ghi lại và chia sẻ với đội tuyển dụng để xem xét."],
  ["The interviewer will ask only the questions configured for this role.", "Người phỏng vấn sẽ chỉ hỏi các câu hỏi đã được cấu hình cho vị trí này."],
  ["You can answer by voice if your browser supports speech recognition, or type into the fallback box.", "Bạn có thể trả lời bằng giọng nói nếu trình duyệt hỗ trợ nhận diện giọng nói, hoặc nhập câu trả lời vào ô dự phòng."],
  ["The interview can be attempted only within the invitation limits set by the recruiter.", "Buổi phỏng vấn chỉ có thể được thực hiện trong giới hạn lời mời mà nhà tuyển dụng đã đặt ra."],
  ["Start interview", "Bắt đầu phỏng vấn"],
  ["Your responses have been submitted. The recruiter can now review the transcript and structured summary.", "Câu trả lời của bạn đã được gửi. Nhà tuyển dụng giờ có thể xem lại bản ghi và phần tóm tắt có cấu trúc."],
  ["Answer transcript", "Bản ghi câu trả lời"],
  ["Speak or type your answer here.", "Nói hoặc nhập câu trả lời của bạn tại đây."],
  ["Stop listening", "Dừng nghe"],
  ["Start listening", "Bắt đầu nghe"],
  ["Speech recognition unavailable, using text fallback", "Không có nhận diện giọng nói, đang dùng chế độ nhập văn bản"],
  ["Page not found.", "Không tìm thấy trang."],
  ["The page you're looking for moved, never existed, or you mistyped the URL.", "Trang bạn đang tìm đã được chuyển đi, chưa từng tồn tại hoặc bạn đã nhập sai URL."],
  ["Back to dashboard", "Quay lại trang tổng quan"],
  ["Sign out", "Đăng xuất"],
  ["Email", "Email"],
  ["Start your free trial", "Bắt đầu dùng thử miễn phí"],
  ["Book a demo", "Đặt lịch xem demo"],
  ["Get started", "Bắt đầu"],
  ["Get started for free", "Bắt đầu miễn phí"],
  ["Resume Parsing", "Phân tích hồ sơ"],
  ["Smart Scoring", "Chấm điểm thông minh"],
  ["Candidate Pools", "Nguồn ứng viên"],
  ["AI Interview Prep", "Chuẩn bị phỏng vấn AI"],
  ["Instantly extract skills and experience from complex PDFs.", "Trích xuất kỹ năng và kinh nghiệm ngay lập tức từ các tệp PDF phức tạp."],
  ["Rank candidates objectively against your specific job descriptions.", "Xếp hạng ứng viên một cách khách quan theo đúng mô tả công việc của bạn."],
  ["Organize talent into dynamic shortlists that evolve over time.", "Sắp xếp ứng viên vào các danh sách chọn lọc linh hoạt và cập nhật theo thời gian."],
  ["Generate tailored interview questions based on candidate profiles.", "Tạo câu hỏi phỏng vấn phù hợp dựa trên hồ sơ ứng viên."],
  ["Scoring Engine", "Bộ máy chấm điểm"],
  ["Stop guessing.", "Đừng phỏng đoán."],
  ["Start measuring.", "Hãy đo lường."],
  ["Our flagship scoring engine breaks down candidates dimension by dimension. Adjust weights for Technical vs Behavioral skills on the fly and see your pool reshuffle instantly.", "Bộ máy chấm điểm chủ lực của chúng tôi phân tách ứng viên theo từng chiều đánh giá. Hãy điều chỉnh trọng số giữa kỹ năng kỹ thuật và hành vi ngay lập tức và xem danh sách ứng viên được sắp xếp lại tức thời."],
  ["Objective baseline for all applicants", "Chuẩn so sánh khách quan cho mọi ứng viên"],
  ["Explainable AI rationales", "Giải thích minh bạch từ AI"],
  ["Identify hidden gems instantly", "Nhanh chóng tìm ra ứng viên tiềm năng"],
  ["AI Assistant", "Trợ lý AI"],
  ["Converse with your", "Trò chuyện với"],
  ["talent pool.", "nguồn ứng viên của bạn."],
  ["Ask natural questions like \"Who has 5+ years of React and lives in Europe?\" The AI recruiter searches, filters, and presents the best matches instantly.", "Hãy hỏi bằng ngôn ngữ tự nhiên như \"Ai có hơn 5 năm kinh nghiệm React và đang sống ở châu Âu?\" Trợ lý tuyển dụng AI sẽ tìm kiếm, lọc và trình bày các ứng viên phù hợp nhất ngay lập tức."],
  ["Ready to find your next great hire?", "Sẵn sàng tìm người phù hợp tiếp theo cho đội ngũ của bạn?"],
  ["No credit card required. 14-day free trial.", "Không cần thẻ tín dụng. Dùng thử miễn phí 14 ngày."],
  ["\"EasyHR completely transformed our hiring pipeline. What used to take our team two weeks of manual screening now happens flawlessly in an afternoon.\"", "\"EasyHR đã thay đổi hoàn toàn quy trình tuyển dụng của chúng tôi. Việc từng mất hai tuần sàng lọc thủ công giờ được hoàn thành mượt mà chỉ trong một buổi chiều.\""],
  ["VP of Talent, Nexus", "Phó Chủ tịch Nhân sự, Nexus"],
  ["© 2030 EasyHR Platform Inc. All rights reserved.", "© 2030 EasyHR Platform Inc. Đã đăng ký bản quyền."],
  ["Privacy", "Quyền riêng tư"],
  ["Terms", "Điều khoản"],
  ["Contact", "Liên hệ"],
  ["Hire like it's", "Tuyển dụng như đang ở năm"],
  ["2030.", "2030."],
  ["The intelligent recruitment platform that turns overwhelming resume piles into curated shortlists, predictive scores, and automated outreach in minutes.", "Nền tảng tuyển dụng thông minh biến những chồng hồ sơ quá tải thành danh sách chọn lọc, điểm dự đoán và quy trình liên hệ tự động chỉ trong vài phút."],
  ["New message", "Tin nhắn mới"],
  ["Compose an outreach message for a candidate.", "Soạn một tin nhắn liên hệ cho ứng viên."],
  ["Select a candidate…", "Chọn một ứng viên…"],
  ["Candidate not found. Please select a different candidate.", "Không tìm thấy ứng viên. Vui lòng chọn một ứng viên khác."],
  ["Content source", "Nguồn nội dung"],
  ["Discard draft? Your changes will be lost.", "Bỏ bản nháp? Các thay đổi của bạn sẽ bị mất."],
  ["Keep editing", "Tiếp tục chỉnh sửa"],
  ["Discard draft", "Bỏ bản nháp"],
  ["Rename collection", "Đổi tên bộ sưu tập"],
  ["From query", "Từ truy vấn"],
  ["A collection with this name already exists.", "Đã có bộ sưu tập với tên này."],
  ["A collection with this name already exists. Please choose a different name.", "Đã có bộ sưu tập với tên này. Vui lòng chọn tên khác."],
  ["More options", "Tùy chọn khác"],
  ["From query", "Từ truy vấn"],
  ["Configure defaults for your recruitment team.", "Cấu hình mặc định cho nhóm tuyển dụng của bạn."],
  ["Workspace configuration options", "Tùy chọn cấu hình workspace"],
  ["Manage keys for programmatic access to the EasyHR API.", "Quản lý các khóa để truy cập lập trình vào API EasyHR."],
  ["Production Key", "Khóa Production"],
  ["Generate new key", "Tạo khóa mới"],
  ["Notification Preferences", "Tùy chọn thông báo"],
  ["Permanently delete your account and all data. This action cannot be undone.", "Xóa vĩnh viễn tài khoản và toàn bộ dữ liệu của bạn. Hành động này không thể hoàn tác."],
  ["Copy application link", "Sao chép liên kết ứng tuyển"],
  ["Open application link", "Mở liên kết ứng tuyển"],
  ["Show QR code", "Hiển thị mã QR"],
  ["This QR code and link are unique to this job.", "Mã QR và liên kết này là duy nhất cho công việc này."],
  ["View candidate", "Xem ứng viên"],
  ["Could not create account. Email may already be in use.", "Không thể tạo tài khoản. Email có thể đã được sử dụng."],
  ["Invalid email or password.", "Email hoặc mật khẩu không hợp lệ."],
  ["Google sign-in failed. Please try again.", "Đăng nhập Google thất bại. Vui lòng thử lại."],
  ["Could not load profile. Please try again.", "Không thể tải hồ sơ. Vui lòng thử lại."],
  ["Hidden Information", "Thông tin ẩn"],
  ["Start scoring", "Bắt đầu chấm điểm"],
  ["Score again", "Chấm điểm lại"],
  ["Total candidates", "Tổng số ứng viên"],
  ["Average score", "Điểm trung bình"],
  ["Highest score", "Điểm cao nhất"],
  ["Score", "Điểm"],
  ["Score Radar", "Biểu đồ điểm"],
  ["Component Scores", "Điểm thành phần"],
  ["Select the current workspace job description…", "Hãy chọn mô tả công việc của workspace hiện tại…"],
  ["Upload resumes to build candidate profiles.", "Tải hồ sơ lên để tạo hồ sơ ứng viên."],
  ["Upload resumes to generate candidate profiles.", "Tải hồ sơ lên để tạo hồ sơ ứng viên."],
  ["Upload resumes or create outreach messages to see activity here.", "Hãy tải hồ sơ lên hoặc tạo tin nhắn liên hệ để xem hoạt động tại đây."],
  ["EasyHR — go to dashboard", "EasyHR — đi đến trang tổng quan"],
  ["Showing 1–2 of 2", "Hiển thị 1–2 / 2"],
  ["Showing 1–1 of 1", "Hiển thị 1–1 / 1"],
  ["Showing 0–0 of 0", "Hiển thị 0–0 / 0"],
  ["Workspace Settings", "Cài đặt workspace"],
  ["Manage your account and workspace preferences", "Quản lý tài khoản và tùy chọn workspace của bạn"],
  ["Profile", "Hồ sơ"],
  ["Workspace", "Không gian làm việc"],
  ["API Keys", "Khóa API"],
  ["Danger Zone", "Vùng nguy hiểm"],
  ["Profile Information", "Thông tin hồ sơ"],
  ["Timezone", "Múi giờ"],
  ["Pacific Time (US & Canada)", "Giờ Thái Bình Dương (Mỹ & Canada)"],
  ["Eastern Time (US & Canada)", "Giờ Miền Đông (Mỹ & Canada)"],
  ["Delete Account", "Xóa tài khoản"],
  ["Delete account", "Xóa tài khoản"],
  ["Public application link", "Liên kết ứng tuyển công khai"],
  ["Copy link", "Sao chép liên kết"],
  ["Copied", "Đã sao chép"],
  ["Apply now", "Ứng tuyển ngay"],
  ["EasyHR application", "Đơn ứng tuyển EasyHR"],
  ["Share your contact details and upload a PDF resume for this role.", "Hãy chia sẻ thông tin liên hệ và tải hồ sơ PDF lên cho vị trí này."],
  ["Upload CV", "Tải CV lên"],
  ["Resume PDF", "Hồ sơ PDF"],
  ["Choose a PDF resume", "Chọn hồ sơ PDF"],
  ["PDF only", "Chỉ nhận PDF"],
  ["No file selected", "Chưa chọn tệp nào"],
  ["Upload your resume", "Tải hồ sơ của bạn lên"],
  ["Choose file", "Chọn tệp"],
  ["Submit resume", "Gửi hồ sơ"],
  ["Submit application", "Gửi hồ sơ ứng tuyển"],
  ["Resume uploaded", "Đã tải hồ sơ lên"],
  ["Search", "Tìm kiếm"],
  ["Filter", "Bộ lọc"],
  ["Status", "Trạng thái"],
  ["All", "Tất cả"],
  ["Newest first", "Mới nhất trước"],
  ["Oldest first", "Cũ nhất trước"],
  ["Processed", "Đã xử lý"],
  ["processed", "đã xử lý"],
  ["Pending", "Đang chờ"],
  ["pending", "đang chờ"],
  ["Failed", "Thất bại"],
  ["failed", "thất bại"],
  ["Sent", "Đã gửi"],
  ["sent", "đã gửi"],
  ["Not sent", "Chưa gửi"],
  ["not sent", "chưa gửi"],
  ["Completed", "Hoàn thành"],
  ["completed", "hoàn thành"],
  ["In progress", "Đang thực hiện"],
  ["in progress", "đang thực hiện"],
  ["Active", "Đang hoạt động"],
  ["active", "đang hoạt động"],
  ["Draft", "Bản nháp"],
  ["draft", "bản nháp"],
  ["Version", "Phiên bản"],
  ["Overall Summary", "Tổng kết chung"],
  ["Communication Summary", "Đánh giá giao tiếp"],
  ["First-time setup", "Thiết lập lần đầu"],
  ["Set up your first job.", "Thiết lập công việc đầu tiên của bạn."],
  ["Choose a hiring workspace.", "Chọn một workspace tuyển dụng."],
  ["Create the workspace context first. You can refine the full job description after you enter the dashboard.", "Hãy tạo ngữ cảnh workspace trước. Bạn có thể hoàn thiện mô tả công việc đầy đủ sau khi vào dashboard."],
  ["Every resume, JD, score, and chat session is scoped to one job.", "Mỗi hồ sơ, JD, lượt chấm điểm và phiên chat đều gắn với một công việc."],
  ["Unable to load workspaces", "Không thể tải workspace"],
  ["The jobs list did not load. Retry once the API is available.", "Danh sách công việc chưa tải được. Hãy thử lại khi API sẵn sàng."],
  ["Retry", "Thử lại"],
  ["Step 1 of 4", "Bước 1 / 4"],
  ["Name the role you are hiring for.", "Đặt tên vị trí bạn đang tuyển."],
  ["This creates the workspace boundary for resumes, job description authoring, scoring runs, and AI recruiter chat.", "Thao tác này tạo phạm vi workspace cho hồ sơ, soạn JD, các lượt chấm điểm và chat AI tuyển dụng."],
  ["Job title", "Tên vị trí"],
  ["Senior Backend Engineer", "Kỹ sư Backend cao cấp"],
  ["Keep it specific. This title will anchor the rest of the hiring workflow.", "Hãy viết cụ thể. Tên vị trí này sẽ làm mốc cho toàn bộ quy trình tuyển dụng phía sau."],
  ["(optional)", "(tùy chọn)"],
  ["optional", "tùy chọn"],
  ["Responsibilities, required skills, or a short hiring brief.", "Trách nhiệm, kỹ năng cần có hoặc một brief tuyển dụng ngắn."],
  ["Core responsibilities", "Trách nhiệm cốt lõi"],
  ["Required skills", "Kỹ năng bắt buộc"],
  ["Hiring priorities", "Ưu tiên tuyển dụng"],
  ["You can edit both fields later.", "Bạn có thể chỉnh sửa cả hai trường sau."],
  ["Create workspace", "Tạo workspace"],
  ["What this unlocks", "Bạn sẽ mở khóa gì"],
  ["Candidate scope", "Phạm vi ứng viên"],
  ["Uploaded resumes stay tied to the right role and pipeline.", "Các hồ sơ đã tải lên sẽ luôn gắn với đúng vị trí và pipeline."],
  ["JD authoring", "Soạn JD"],
  ["You can expand this into a full job description when ready.", "Bạn có thể mở rộng phần này thành mô tả công việc đầy đủ khi sẵn sàng."],
  ["AI recruiter chat", "Chat AI tuyển dụng"],
  ["Chat answers stay grounded in the selected job workspace.", "Các câu trả lời chat sẽ luôn bám theo workspace công việc đã chọn."],
  ["Recommended next", "Gợi ý bước tiếp theo"],
  ["Add the full job description to define fit.", "Thêm mô tả công việc đầy đủ để xác định mức độ phù hợp."],
  ["Run scoring once both are ready.", "Chạy chấm điểm khi cả hai đã sẵn sàng."],
  ["Use AI chat to interrogate the pipeline.", "Dùng chat AI để khai thác pipeline ứng viên."],
  ["The dashboard will guide the rest of the setup after this step.", "Dashboard sẽ hướng dẫn các bước thiết lập còn lại sau bước này."],
  ["You can switch jobs anytime from the top bar.", "Bạn có thể chuyển công việc bất kỳ lúc nào từ thanh trên cùng."],
  ["Search jobs...", "Tìm công việc..."],
  ["Search jobs", "Tìm công việc"],
  ["Follow-Up Topics", "Các chủ đề cần theo dõi"],
  ["Candidate Overview", "Tổng quan ứng viên"],
  ["Competencies", "Năng lực"],
  ["Evidence:", "Bằng chứng:"],
  ["None noted", "Không có"],
  ["Selected job", "Công việc đã chọn"],
  ["Select job", "Chọn công việc"],
  ["Search (Cmd K)", "Tìm kiếm (Cmd K)"],
  ["Jobs / New", "Công việc / Mới"],
  ["Jobs / Edit", "Công việc / Chỉnh sửa"],
  ["Jobs / Job Description", "Công việc / Mô tả công việc"],
  ["Shortlists / Collection", "Danh sách chọn lọc / Bộ sưu tập"],
  ["Interview Reports", "Báo cáo phỏng vấn"],
  ["Notifications", "Thông báo"],
  ["Command palette", "Bảng lệnh"],
  ["User menu", "Menu người dùng"],
  ["Setup", "Thiết lập"],
  ["Processing", "Đang xử lý"],
  ["Results", "Kết quả"],
  ["All candidates", "Tất cả ứng viên"],
  ["Specific candidates", "Ứng viên cụ thể"],
  ["Section Weights", "Trọng số tiêu chí"],
  ["Skills", "Kỹ năng"],
  ["Experience", "Kinh nghiệm"],
  ["Education", "Học vấn"],
  ["Projects", "Dự án"],
  ["Summary", "Tóm tắt"],
  ["Add section", "Thêm tiêu chí"],
  ["Configuration", "Cấu hình"],
  ["Pass threshold", "Ngưỡng đạt"],
  ["0 — score all", "0 — chấm tất cả"],
  ["100 — perfect only", "100 — chỉ chấp nhận tuyệt đối"],
  ["Internal criteria, preferred signals, red flags, compensation constraints...", "Tiêu chí nội bộ, tín hiệu ưu tiên, dấu hiệu cảnh báo, ràng buộc lương..."],
  ["Create a workspace for one role, candidate pool, JD, scoring history, and AI chat context.", "Tạo workspace cho một vị trí, danh sách ứng viên, JD, lịch sử chấm điểm và ngữ cảnh trò chuyện AI."],
  ["Job title", "Tên vị trí"],
  ["Senior Backend Engineer", "Kỹ sư Backend cao cấp"],
  ["Archived", "Đã lưu trữ"],
  ["Candidate upload link", "Liên kết ứng viên tải hồ sơ"],
  ["This controls whether candidates can submit resumes through the public link and QR code for this job.", "Mục này quyết định ứng viên có thể nộp hồ sơ qua liên kết công khai và mã QR của công việc này hay không."],
  ["Enabled", "Đã bật"],
  ["Candidate message", "Tin nhắn cho ứng viên"],
  ["Add instructions candidates will see before uploading their PDF.", "Thêm hướng dẫn để ứng viên nhìn thấy trước khi tải file PDF lên."],
  ["What belongs to a job?", "Một công việc bao gồm những gì?"],
  ["One JD, uploaded resumes, parsed candidate profiles, score runs, and chat context.", "Một JD, các hồ sơ đã tải lên, hồ sơ ứng viên đã được phân tích, các lượt chấm điểm và ngữ cảnh trò chuyện."],
  ["Workspace preview", "Xem trước workspace"],
  ["Untitled job", "Công việc chưa đặt tên"],
  ["This workspace will define the data boundary for the rest of the recruiting pipeline.", "Workspace này sẽ xác định phạm vi dữ liệu cho toàn bộ pipeline tuyển dụng còn lại."],
  ["Get started", "Bắt đầu"],
  ["Complete these steps to set up your recruitment workflow.", "Hoàn thành các bước này để thiết lập quy trình tuyển dụng."],
  ["0 of 4 complete", "Hoàn thành 0/4 bước"],
  ["1 of 4 complete", "Hoàn thành 1/4 bước"],
  ["2 of 4 complete", "Hoàn thành 2/4 bước"],
  ["3 of 4 complete", "Hoàn thành 3/4 bước"],
  ["4 of 4 complete", "Hoàn thành 4/4 bước"],
  ["Upload your first resumes", "Tải những hồ sơ đầu tiên"],
  ["Parse PDF CVs into structured candidate profiles", "Phân tích CV PDF thành hồ sơ ứng viên có cấu trúc"],
  ["Add the full job description", "Thêm mô tả công việc đầy đủ"],
  ["Capture responsibilities, requirements, and hiring notes", "Lưu lại trách nhiệm, yêu cầu và ghi chú tuyển dụng"],
  ["Run AI scoring", "Chạy chấm điểm AI"],
  ["Compare candidates once resumes and the JD are ready", "So sánh ứng viên khi hồ sơ và JD đã sẵn sàng"],
  ["Ask the AI Recruiter", "Hỏi trợ lý tuyển dụng AI"],
  ["Interrogate your candidate pool after data starts flowing in", "Khai thác danh sách ứng viên khi dữ liệu bắt đầu được đổ vào"],
  ["Total Candidates", "Tổng số ứng viên"],
  ["Processed Today", "Đã xử lý hôm nay"],
  ["Active JDs", "JD đang hoạt động"],
  ["Pending Outreach", "Liên hệ đang chờ"],
  ["Recent Activity", "Hoạt động gần đây"],
  ["View all →", "Xem tất cả →"],
  ["Quick Actions", "Thao tác nhanh"],
  ["Parse new PDF CVs", "Phân tích CV PDF mới"],
  ["Create JD", "Tạo JD"],
  ["Write a new job description", "Viết mô tả công việc mới"],
  ["Rank candidates by fit", "Xếp hạng ứng viên theo mức độ phù hợp"],
  ["Open AI Chat", "Mở trò chuyện AI"],
  ["Query your candidate pool", "Truy vấn danh sách ứng viên"],
  ["AI Insight", "Nhận định AI"],
  ["Start by uploading your first resumes.", "Hãy bắt đầu bằng việc tải những hồ sơ đầu tiên lên."],
  ["Parse PDFs to build candidate profiles and unlock AI scoring.", "Phân tích PDF để tạo hồ sơ ứng viên và mở khóa tính năng chấm điểm AI."],
  ["Keep uploading resumes and scoring candidates to surface top matches.", "Hãy tiếp tục tải hồ sơ lên và chấm điểm ứng viên để làm nổi bật các hồ sơ phù hợp nhất."],
  ["No prior data", "Chưa có dữ liệu trước đó"],
]);

const inlineTranslations: Array<[string, string]> = [
  ["Good morning, ", "Chào buổi sáng, "],
  ["Good afternoon, ", "Chào buổi chiều, "],
  ["Good evening, ", "Chào buổi tối, "],
  ["Current workspace", "Workspace hiện tại"],
  ["Current job", "Công việc hiện tại"],
  ["Public job description", "Mô tả công việc công khai"],
  ["Recruiter-only hidden information", "Thông tin ẩn chỉ dành cho nhà tuyển dụng"],
  ["Overall score", "Điểm tổng"],
  ["Strong matches:", "Điểm mạnh:"],
  ["Gaps:", "Khoảng trống:"],
  ["Partial matches:", "Phù hợp một phần:"],
  ["Matched requirement for", "Đáp ứng yêu cầu cho"],
  ["Did not match requirement for", "Chưa đáp ứng yêu cầu cho"],
  ["Matched boolean requirement for", "Đáp ứng điều kiện logic cho"],
  ["Did not match boolean requirement for", "Chưa đáp ứng điều kiện logic cho"],
  ["expected", "kỳ vọng"],
  ["candidate has", "ứng viên có"],
  ["candidate is", "ứng viên là"],
  ["Job:", "Vị trí:"],
  ["Monday", "Thứ Hai"],
  ["Mon", "Th 2"],
  ["Tuesday", "Thứ Ba"],
  ["Tue", "Th 3"],
  ["Wednesday", "Thứ Tư"],
  ["Wed", "Th 4"],
  ["Thursday", "Thứ Năm"],
  ["Thu", "Th 5"],
  ["Friday", "Thứ Sáu"],
  ["Fri", "Th 6"],
  ["Saturday", "Thứ Bảy"],
  ["Sat", "Th 7"],
  ["Sunday", "Chủ Nhật"],
  ["Sun", "CN"],
  ["January", "Tháng Một"],
  ["Jan", "Thg 1"],
  ["February", "Tháng Hai"],
  ["Feb", "Thg 2"],
  ["March", "Tháng Ba"],
  ["Mar", "Thg 3"],
  ["April", "Tháng Tư"],
  ["Apr", "Thg 4"],
  ["May", "Tháng Năm"],
  ["June", "Tháng Sáu"],
  ["Jun", "Thg 6"],
  ["July", "Tháng Bảy"],
  ["Jul", "Thg 7"],
  ["August", "Tháng Tám"],
  ["Aug", "Thg 8"],
  ["September", "Tháng Chín"],
  ["Sep", "Thg 9"],
  ["October", "Tháng Mười"],
  ["Oct", "Thg 10"],
  ["November", "Tháng Mười Một"],
  ["Nov", "Thg 11"],
  ["December", "Tháng Mười Hai"],
  ["Dec", "Thg 12"],
  ["vs last week", "so với tuần trước"],
  [" ago", " trước"],
];

const regexTranslations: Array<[RegExp, string]> = [
  [/^Showing\s+(.+)\s+of\s+(\d+)$/u, "Hiển thị $1 / $2"],
  [/^Version\s+(.+)$/u, "Phiên bản $1"],
  [/^Job:\s*/u, "Vị trí: "],
  [/^(\d+)\s+of\s+(\d+)\s+complete$/u, "Hoàn thành $1/$2 bước"],
  [/^(\d+)\s+candidate$/u, "$1 ứng viên"],
  [/^(\d+)\s+candidates$/u, "$1 ứng viên"],
  [/^(\d+)\s+turn$/u, "$1 lượt"],
  [/^(\d+)\s+turns$/u, "$1 lượt"],
  [/^Created\s+(.+)$/u, "Tạo lúc $1"],
  [/^Updated\s+(.+)$/u, "Cập nhật $1"],
  [/^Uploaded\s+(.+)$/u, "Tải lên $1"],
  [/^Expires\s+(.+)$/u, "Hết hạn $1"],
  [/^Attempts\s+(.+)$/u, "Lượt thử $1"],
  [/^Saved just now$/u, "Vừa lưu xong"],
  [/^Saved\s+(\d+)s ago$/u, "Đã lưu $1 giây trước"],
  [/^Saved\s+(\d+)m ago$/u, "Đã lưu $1 phút trước"],
  [/^Delete\s+(\d+)\s+resumes$/u, "Xóa $1 hồ sơ"],
];

const attributeNames = ["placeholder", "aria-label", "title"] as const;

function translateCore(text: string) {
  if (!text) return text;

  const exact = exactTranslations.get(text);
  if (exact) return exact;

  let next = text;

  for (const [pattern, replacement] of regexTranslations) {
    next = next.replace(pattern, replacement);
  }

  for (const [source, target] of inlineTranslations) {
    if (next.includes(source)) {
      next = next.split(source).join(target);
    }
  }

  return next;
}

function translateText(text: string) {
  const leading = text.match(/^\s*/u)?.[0] ?? "";
  const trailing = text.match(/\s*$/u)?.[0] ?? "";
  const core = text.slice(leading.length, text.length - trailing.length);
  if (!core) return text;
  return `${leading}${translateCore(core)}${trailing}`;
}

function shouldSkipElement(element: Element) {
  const tagName = element.tagName.toLowerCase();
  return tagName === "script" || tagName === "style";
}

function translateNode(node: Node) {
  if (node.nodeType === Node.TEXT_NODE) {
    const original = node.textContent ?? "";
    const translated = translateText(original);
    if (translated !== original) {
      node.textContent = translated;
    }
    return;
  }

  if (node.nodeType !== Node.ELEMENT_NODE) return;

  const element = node as Element;

  for (const attributeName of attributeNames) {
    const originalValue = element.getAttribute(attributeName);
    if (!originalValue) continue;
    const translatedValue = translateText(originalValue);
    if (translatedValue !== originalValue) {
      element.setAttribute(attributeName, translatedValue);
    }
  }

  if (shouldSkipElement(element)) return;

  for (const child of Array.from(element.childNodes)) {
    translateNode(child);
  }
}

export function UiLocalizer() {
  useEffect(() => {
    if (!isVietnameseUi()) {
      document.documentElement.lang = "en";
      return;
    }

    document.documentElement.lang = "vi";

    const root = document.body;
    if (!root) return;

    translateNode(root);

    const observer = new MutationObserver((mutations) => {
      for (const mutation of mutations) {
        if (mutation.type === "characterData") {
          translateNode(mutation.target);
          continue;
        }

        if (mutation.type === "attributes" && mutation.target instanceof Element) {
          translateNode(mutation.target);
          continue;
        }

        for (const addedNode of Array.from(mutation.addedNodes)) {
          translateNode(addedNode);
        }
      }

      translateNode(root);
    });

    observer.observe(root, {
      subtree: true,
      childList: true,
      characterData: true,
      attributes: true,
      attributeFilter: [...attributeNames],
    });

    return () => observer.disconnect();
  }, []);

  return null;
}
